/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProjectResource service. Represents a row in the &quot;timesheet_ProjectResource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.timesheet.model.impl.ProjectResourceModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.timesheet.model.impl.ProjectResourceImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectResource
 * @generated
 */
@ProviderType
public interface ProjectResourceModel
	extends BaseModel<ProjectResource>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project resource model instance should use the {@link ProjectResource} interface instead.
	 */

	/**
	 * Returns the primary key of this project resource.
	 *
	 * @return the primary key of this project resource
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project resource.
	 *
	 * @param primaryKey the primary key of this project resource
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project resource.
	 *
	 * @return the uuid of this project resource
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project resource.
	 *
	 * @param uuid the uuid of this project resource
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project resource ID of this project resource.
	 *
	 * @return the project resource ID of this project resource
	 */
	public long getProjectResourceId();

	/**
	 * Sets the project resource ID of this project resource.
	 *
	 * @param projectResourceId the project resource ID of this project resource
	 */
	public void setProjectResourceId(long projectResourceId);

	/**
	 * Returns the group ID of this project resource.
	 *
	 * @return the group ID of this project resource
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project resource.
	 *
	 * @param groupId the group ID of this project resource
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project resource.
	 *
	 * @return the company ID of this project resource
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project resource.
	 *
	 * @param companyId the company ID of this project resource
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project resource.
	 *
	 * @return the user ID of this project resource
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project resource.
	 *
	 * @param userId the user ID of this project resource
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project resource.
	 *
	 * @return the user uuid of this project resource
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project resource.
	 *
	 * @param userUuid the user uuid of this project resource
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project resource.
	 *
	 * @return the user name of this project resource
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project resource.
	 *
	 * @param userName the user name of this project resource
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project resource.
	 *
	 * @return the create date of this project resource
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project resource.
	 *
	 * @param createDate the create date of this project resource
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project resource.
	 *
	 * @return the modified date of this project resource
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project resource.
	 *
	 * @param modifiedDate the modified date of this project resource
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the end date of this project resource.
	 *
	 * @return the end date of this project resource
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this project resource.
	 *
	 * @param endDate the end date of this project resource
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the start date of this project resource.
	 *
	 * @return the start date of this project resource
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this project resource.
	 *
	 * @param startDate the start date of this project resource
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the project ID of this project resource.
	 *
	 * @return the project ID of this project resource
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project resource.
	 *
	 * @param projectId the project ID of this project resource
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the employee ID of this project resource.
	 *
	 * @return the employee ID of this project resource
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this project resource.
	 *
	 * @param employeeId the employee ID of this project resource
	 */
	public void setEmployeeId(long employeeId);

}