/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TaskCategory service. Represents a row in the &quot;timesheet_TaskCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.adjecti.timesheet.model.impl.TaskCategoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.adjecti.timesheet.model.impl.TaskCategoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TaskCategory
 * @generated
 */
@ProviderType
public interface TaskCategoryModel
	extends BaseModel<TaskCategory>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task category model instance should use the {@link TaskCategory} interface instead.
	 */

	/**
	 * Returns the primary key of this task category.
	 *
	 * @return the primary key of this task category
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task category.
	 *
	 * @param primaryKey the primary key of this task category
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task category.
	 *
	 * @return the uuid of this task category
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task category.
	 *
	 * @param uuid the uuid of this task category
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task category ID of this task category.
	 *
	 * @return the task category ID of this task category
	 */
	public long getTaskCategoryId();

	/**
	 * Sets the task category ID of this task category.
	 *
	 * @param taskCategoryId the task category ID of this task category
	 */
	public void setTaskCategoryId(long taskCategoryId);

	/**
	 * Returns the group ID of this task category.
	 *
	 * @return the group ID of this task category
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task category.
	 *
	 * @param groupId the group ID of this task category
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task category.
	 *
	 * @return the company ID of this task category
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task category.
	 *
	 * @param companyId the company ID of this task category
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task category.
	 *
	 * @return the user ID of this task category
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task category.
	 *
	 * @param userId the user ID of this task category
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task category.
	 *
	 * @return the user uuid of this task category
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this task category.
	 *
	 * @param userUuid the user uuid of this task category
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task category.
	 *
	 * @return the user name of this task category
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task category.
	 *
	 * @param userName the user name of this task category
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task category.
	 *
	 * @return the create date of this task category
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task category.
	 *
	 * @param createDate the create date of this task category
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task category.
	 *
	 * @return the modified date of this task category
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task category.
	 *
	 * @param modifiedDate the modified date of this task category
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the type of this task category.
	 *
	 * @return the type of this task category
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this task category.
	 *
	 * @param type the type of this task category
	 */
	public void setType(String type);

}